<a href="https://colab.research.google.com/github/Rijan-Ja-Bhattarai/AI/blob/main/Exercise01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create a random tensor of (7, 7)

In [1]:
import torch

In [2]:
size_seven_by_seven_tensor = torch.rand(size = (1, 7, 7))
size_seven_by_seven_tensor

tensor([[[0.4699, 0.5749, 0.4867, 0.9640, 0.8836, 0.0127, 0.3226],
         [0.3827, 0.7043, 0.6548, 0.1299, 0.8368, 0.9264, 0.6126],
         [0.0341, 0.8144, 0.5508, 0.0845, 0.7116, 0.6915, 0.6126],
         [0.0437, 0.4022, 0.8247, 0.9289, 0.5720, 0.4045, 0.1396],
         [0.6626, 0.9980, 0.9690, 0.1601, 0.0031, 0.9802, 0.6560],
         [0.5974, 0.9101, 0.2390, 0.6229, 0.3012, 0.5451, 0.1630],
         [0.8891, 0.3520, 0.7577, 0.4157, 0.6138, 0.2501, 0.5196]]])

# Perform Matrix Multiplication Between 2 Tensors

In [3]:
tensor_A = torch.rand(size = (1, 1, 7))
tensor_A

tensor([[[0.1802, 0.6261, 0.6825, 0.5648, 0.6338, 0.5768, 0.7062]]])

In [4]:
# Peform matmul
mul_tensor = torch.matmul(tensor_A, size_seven_by_seven_tensor)
mul_tensor

tensor([[[1.7647, 2.7336, 2.6265, 1.5916, 2.1011, 2.3949, 1.8154]]])

# Create a Random Seed and do the matmul again

In [5]:
torch.manual_seed(777)
size_seven_by_seven_tensor = torch.rand(size = (1, 7, 7))

torch.manual_seed(777)
tensor_A = torch.rand(size = (1, 1, 7))

print(f"Tensor A: \n{size_seven_by_seven_tensor}")
print(f"Tensor B: \n{tensor_A}")

print(f"Shape of Tensor A: {size_seven_by_seven_tensor.shape}")
print(f"Shape of Tensor B: {tensor_A.shape}")


print(f"{size_seven_by_seven_tensor == tensor_A}")

mul_tensor = torch.matmul(tensor_A, size_seven_by_seven_tensor)
print(f"Multiplied Tensors: \n{mul_tensor}")
print(f"Shape of Multiplied Tensor: {mul_tensor.shape}")

Tensor A: 
tensor([[[0.0819, 0.4911, 0.4033, 0.3859, 0.8813, 0.8811, 0.7242],
         [0.5033, 0.8249, 0.2634, 0.3112, 0.5948, 0.1092, 0.6213],
         [0.7350, 0.9898, 0.9165, 0.3246, 0.8715, 0.8875, 0.9036],
         [0.2204, 0.3996, 0.2329, 0.9411, 0.9180, 0.8952, 0.4341],
         [0.1523, 0.3154, 0.3771, 0.6166, 0.5355, 0.9970, 0.3777],
         [0.9541, 0.8282, 0.6459, 0.5544, 0.3703, 0.0696, 0.3870],
         [0.7293, 0.9067, 0.0059, 0.0251, 0.4496, 0.2148, 0.3932]]])
Tensor B: 
tensor([[[0.0819, 0.4911, 0.4033, 0.3859, 0.8813, 0.8811, 0.7242]]])
Shape of Tensor A: torch.Size([1, 7, 7])
Shape of Tensor B: torch.Size([1, 1, 7])
tensor([[[ True,  True,  True,  True,  True,  True,  True],
         [False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False],
         [False, False, False, False, False, False, Fals

# Set the random seed on the GPU

In [11]:
torch.cuda.manual_seed(1234)
tensor_A = torch.rand(3, 4, device="cuda")
tensor_A

tensor([[0.1272, 0.8167, 0.5440, 0.6601],
        [0.2721, 0.9737, 0.3903, 0.3394],
        [0.5451, 0.7312, 0.3864, 0.5959]], device='cuda:0')

# Send Two Tensors From CPU to The GPU

In [18]:
torch.cuda.manual_seed(1234)
tensor_A = torch.rand(2, 3)

torch.cuda.manual_seed(1234)
tensor_B = torch.rand(2, 3)

tensor_A.device, tensor_B.device

(device(type='cpu'), device(type='cpu'))

In [19]:
tensor_A_gpu = tensor_A.to("cuda")
tensor_B_gpu = tensor_B.to("cuda")

tensor_A_gpu.device, tensor_B_gpu.device

(device(type='cuda', index=0), device(type='cuda', index=0))

# Matmul of Two Tensors in the GPU

In [22]:
gpu_mat_mul = tensor_A_gpu @ tensor_B_gpu.T
print(f"Matrix Multiplication on GPU: {gpu_mat_mul}")

Matrix Multiplication on GPU: tensor([[0.4750, 0.3144],
        [0.5044, 0.6514]], device='cuda:0')


# Finding the Max and Min of Matmul Matrix

In [24]:
max_val = gpu_mat_mul.max()
min_val = gpu_mat_mul.min()
max_val_index = gpu_mat_mul.argmax()
min_val_index = gpu_mat_mul.argmin()

print(f"Max Value: {max_val}")
print(f"Min Value: {min_val}")
print(f"Max Value Index: {max_val_index}")
print(f"Min Value Index: {min_val_index}")


Max Value: 0.6513799428939819
Min Value: 0.31441301107406616
Max Value Index: 3
Min Value Index: 1


# Creating a tensor and removing 1 dimensions from it

In [27]:
torch.manual_seed(7)
tensor_C = torch.rand(1, 1, 1, 10)
tensor_D = tensor_C.squeeze()

print(f"Tensor C: \n{tensor_C}")
print(f"Tensor D: \n{tensor_D}")

print(f"Tensor C shape: {tensor_C.shape}")
print(f"Tensor D shape: {tensor_D.shape}")

Tensor C: 
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Tensor D: 
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Tensor C shape: torch.Size([1, 1, 1, 10])
Tensor D shape: torch.Size([10])
